### ISSUE TITLE
Error precompiling assets in preproduction

### ISSUE THREAD

**Issue by copperx** [rubysamurai/material_components_web-sass#3]
I'm getting a SASS error when precompiling assets on production; this doesn't happen when precompiling on development mode.

```
Sass::SyntaxError: Invalid CSS after "...minmax(0, 1fr))": expected ";", was "[12];"
(sass):31062
```

It may be related to this: https://github.com/material-components/material-components-web/issues/278

I'm using SASS 3.4.23.

Any ideas?

**Comment by rubysamurai** [comment]
Hello,
I actually remember seeing this error, caused by [this line](https://github.com/rubysamurai/material_components_web-sass/blob/8476ac1164a0781518b48add081916c1d122ea62/vendor/assets/stylesheets/%40material/layout-grid/_mixins.scss#L86), once, but I couldn't reproduce again, using either existing app or a new one.

Could you please try bundle update and then try to precompile again.

```
$ bundle update
$ RAILS_ENV=production rake assets:clobber assets:precompile
```

If this error persists, provide please you `Gemfile` content.

P.S.
Regarding [material-components-web/issues/278](https://github.com/material-components/material-components-web/issues/278), it is fixed in this gem, but since MDC team doesn't officially support Sass 3.4 and Rails Assets pipeline can't use Sass 4 (for now), there might be new problems eventually.

**Comment by phillycheeze** [comment]
I am too getting this same exact error. I am on `0.12.1`

The command I run: `bundle exec rake assets:precompile RAILS_ENV=production`

I already ran `assets:clean` and that didn't help. 

Full error log:

```
rake aborted!
Sass::SyntaxError: Invalid CSS after "...minmax(0, 1fr))": expected ";", was "[12];"
(sass):19744
/var/www/current/app/assets/config/manifest.js:3
(sass):19744
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:1207:in `expected'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:1137:in `expected'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:1132:in `tok!'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:786:in `block in try_declaration'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:1183:in `rethrow'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:791:in `try_declaration'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:720:in `declaration_or_ruleset'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:685:in `block_child'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:674:in `block_contents'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:666:in `block'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:735:in `declaration_or_ruleset'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:685:in `block_child'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:674:in `block_contents'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:666:in `block'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:409:in `media_directive'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:222:in `special_directive'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:197:in `directive'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:685:in `block_child'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:677:in `block_contents'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:554:in `supports_directive'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:227:in `prefixed_directive'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:199:in `directive'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:684:in `block_child'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:677:in `block_contents'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:125:in `stylesheet'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/scss/parser.rb:41:in `parse'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/engine.rb:406:in `_to_tree'
/var/lib/gems/2.4.0/gems/sass-3.4.24/lib/sass/engine.rb:281:in `render'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/sass_compressor.rb:48:in `call'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/sass_compressor.rb:28:in `call'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:388:in `load'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:357:in `block in link_paths'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:367:in `block in resolve_paths'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:363:in `each'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:363:in `resolve_paths'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:356:in `link_paths'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:317:in `process_link_directory_directive'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:180:in `block in process_directives'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `each'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:178:in `process_directives'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:83:in `_call'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/directive_processor.rb:68:in `call'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/var/lib/gems/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/var/lib/gems/2.4.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/var/lib/gems/2.4.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/var/lib/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```
Here are the contents of my Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.1.1)
      actionpack (= 5.1.1)
      nio4r (~> 2.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.1.1)
      actionpack (= 5.1.1)
      actionview (= 5.1.1)
      activejob (= 5.1.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.1.1)
      actionview (= 5.1.1)
      activesupport (= 5.1.1)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.1.1)
      activesupport (= 5.1.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.1.1)
      activesupport (= 5.1.1)
      globalid (>= 0.3.6)
    activemodel (5.1.1)
      activesupport (= 5.1.1)
    activerecord (5.1.1)
      activemodel (= 5.1.1)
      activesupport (= 5.1.1)
      arel (~> 8.0)
    activesupport (5.1.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.1)
      public_suffix (~> 2.0, >= 2.0.2)
    arel (8.0.0)
    autoprefixer-rails (6.7.7.2)
      execjs
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    bindex (0.5.0)
    builder (3.2.3)
    byebug (9.0.6)
    capybara (2.13.0)
      addressable
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    childprocess (0.7.0)
      ffi (~> 1.0, >= 1.0.11)
    coderay (1.1.1)
    concurrent-ruby (1.0.5)
    config (1.4.0)
      activesupport (>= 3.0)
      deep_merge (~> 1.1.1)
    deep_merge (1.1.1)
    diff-lcs (1.3)
    dotenv (2.2.1)
    dotenv-rails (2.2.1)
      dotenv (= 2.2.1)
      railties (>= 3.2, < 5.2)
    erubi (1.6.0)
    erubis (2.7.0)
    execjs (2.7.0)
    faraday (0.12.1)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.18)
    globalid (0.4.0)
      activesupport (>= 4.2.0)
    hashie (3.5.5)
    httparty (0.14.0)
      multi_xml (>= 0.5.2)
    i18n (0.8.4)
    jbuilder (2.7.0)
      activesupport (>= 4.2.0)
      multi_json (>= 1.2)
    jquery-rails (4.3.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jwt (1.5.6)
    libv8 (3.16.14.19)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.6)
      mime-types (>= 1.16, < 4)
    material_components_web-sass (0.12.1)
      autoprefixer-rails (>= 6.5)
      sass (>= 3.4)
    material_design_lite-sass (1.3.0)
      autoprefixer-rails (~> 6.0)
      sass (~> 3.3)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mina (1.0.6)
      open4 (~> 1.3.4)
      rake
    mini_portile2 (2.2.0)
    minitest (5.10.2)
    multi_json (1.12.1)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    nio4r (2.1.0)
    nokogiri (1.8.0)
      mini_portile2 (~> 2.2.0)
    oauth2 (1.4.0)
      faraday (>= 0.8, < 0.13)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.6.1)
      hashie (>= 3.4.6, < 3.6.0)
      rack (>= 1.6.2, < 3)
    omniauth-google-oauth2 (0.5.0)
      jwt (~> 1.5)
      multi_json (~> 1.3)
      omniauth (>= 1.1.1)
      omniauth-oauth2 (>= 1.3.1)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    open4 (1.3.4)
    pdf-core (0.7.0)
    pg (0.20.0)
    prawn (2.2.2)
      pdf-core (~> 0.7.0)
      ttfunk (~> 1.5)
    prawn-rails (1.0.0)
      prawn
      prawn-table
      rails (>= 3.1.0)
    prawn-table (0.2.2)
      prawn (>= 1.3.0, < 3.0.0)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-byebug (3.4.2)
      byebug (~> 9.0)
      pry (~> 0.10)
    pry-rails (0.3.6)
      pry (>= 0.10.4)
    public_suffix (2.0.5)
    rack (2.0.3)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.1.1)
      actioncable (= 5.1.1)
      actionmailer (= 5.1.1)
      actionpack (= 5.1.1)
      actionview (= 5.1.1)
      activejob (= 5.1.1)
      activemodel (= 5.1.1)
      activerecord (= 5.1.1)
      activesupport (= 5.1.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.1.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (5.1.1)
      actionpack (= 5.1.1)
      activesupport (= 5.1.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.0.0)
    rb-fsevent (0.9.8)
    rb-inotify (0.9.8)
      ffi (>= 0.5.0)
    ref (2.0.0)
    rspec-core (3.6.0)
      rspec-support (~> 3.6.0)
    rspec-expectations (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-mocks (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-rails (3.6.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.6.0)
      rspec-expectations (~> 3.6.0)
      rspec-mocks (~> 3.6.0)
      rspec-support (~> 3.6.0)
    rspec-support (3.6.0)
    ruby_dep (1.5.0)
    rubyzip (1.2.1)
    sass (3.4.24)
    sass-rails (5.0.6)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    selenium-webdriver (3.4.1)
      childprocess (~> 0.5)
      rubyzip (~> 1.0)
    slop (3.6.0)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.3.13)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref
    thor (0.19.4)
    thread_safe (0.3.6)
    tilt (2.0.7)
    ttfunk (1.5.1)
    tzinfo (1.2.3)
      thread_safe (~> 0.1)
    uglifier (3.2.0)
      execjs (>= 0.3.0, < 3)
    web-console (3.5.1)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)
    xpath (2.1.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  better_errors
  byebug
  capybara (~> 2.13.0)
  config
  dotenv-rails
  httparty (= 0.14.0)
  jbuilder (~> 2.5)
  jquery-rails
  listen (>= 3.0.5, < 3.2)
  material_components_web-sass (= 0.12.1)
  material_design_lite-sass (= 1.3.0)
  mina
  omniauth-google-oauth2
  pg (= 0.20.0)
  prawn-rails
  pry-byebug
  pry-rails
  rails (~> 5.1.0)
  rspec-rails (~> 3.5)
  sass-rails (~> 5.0)
  selenium-webdriver
  spring
  spring-watcher-listen (~> 2.0.0)
  sqlite3
  therubyracer
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)

BUNDLED WITH
   1.14.6
```

**Comment by rubysamurai** [comment]
Thank you for `Gemfile.lock` data. Can reproduce the issue now.

But so far I can't understand where it comes from. The `.scss` line it complains about is absolutely correct and taken directly from the official MDC repo without any modification, the gem itself passes all sass compilation tests too.

And what's more interesting, fetching gem directly from github like this:

```
gem 'material_components_web-sass', github: 'rubysamurai/material_components_web-sass'
```

Make precompile error disappear for me. Could you please try it?

**Comment by phillycheeze** [comment]
I tried replacing it with the github version, but I still get the same issue. Very odd that it makes it disappear for you.

**Comment by rubysamurai** [comment]
Please try again using github source. Tried to just remove that problematic semicolon (that should still be a valid Sass code).

**Comment by rubysamurai** [comment]
Just updated repo with latest MDC v0.13.0 assets. No error for me again using GitHub as a gem source, but will test some more before pushing new gem to RubyGems.

**Comment by phillycheeze** [comment]
So I tried completely wiping my virtual machine and restarting from scratch, and it still comes up with the same error.

**Comment by phillycheeze** [comment]
Could you send me your Gemfile.lock that makes it able to work for you? :)

**Comment by rubysamurai** [comment]
Does 

```
gem 'material_components_web-sass', github: 'rubysamurai/material_components_web-sass'
```

And 

```
gem 'material_components_web-sass', github: 'rubysamurai/material_components_web-sass', ref: '5617d'
```

Both throws an error too? That last one has problematic semicolon removed.

**Comment by phillycheeze** [comment]
I tried commit `5617dfd744a8777ebe8266c3b4e4e280d3100902` and the latest`1741ab9094e6f1d60c0ea1a9d042ddca94db3964`.

Maybe it is a problem with sass or sprockets.

**Comment by rubysamurai** [comment]
Could you please paste an error with commit 5617d? The semicolon is removed there, so at least it should be slightly different from original one.

And yes, there are definitely issues with rails assets pipeline and MDC code. Up to the point where the best way to integrate MDC would be Webpacker that comes now by default with Rails 5.1.

**Comment by phillycheeze** [comment]
For commit 5617d, I get the same error as before. I even tried to downgrade the sass-rails gem and sass gem one version down (from 5.0.6 -> 5.0.5) and still the same error. I also completely remove all gems and run assets:clean before each run. Here is the error again:

```
rake aborted!
       Sass::SyntaxError: Invalid CSS after "...minmax(0, 1fr))": expected ";", was "[12];"
       (sass):19744
       /var/www/current/app/assets/config/manifest.js:3
       (sass):19744
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:1207:in `expected'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:1137:in `expected'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:1132:in `tok!'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:786:in `block in try_declaration'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:1183:in `rethrow'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:791:in `try_declaration'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:720:in `declaration_or_ruleset'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:685:in `block_child'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:674:in `block_contents'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:666:in `block'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:735:in `declaration_or_ruleset'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:685:in `block_child'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:674:in `block_contents'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:666:in `block'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:409:in `media_directive'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:222:in `special_directive'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:197:in `directive'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:685:in `block_child'
       /var/www/current/vendor/bundle/ruby/2.4.0/gems/sass-3.4.23/lib/sass/scss/parser.rb:677:in `block_contents'
```

**Comment by phillycheeze** [comment]
Latest Gemfile.lock:
```
GIT
  remote: https://github.com/rubysamurai/material_components_web-sass.git
  revision: 5617dfd744a8777ebe8266c3b4e4e280d3100902
  ref: 5617d
  specs:
    material_components_web-sass (0.12.1)
      autoprefixer-rails (>= 6.5)
      sass (>= 3.4)

GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.1.1)
      actionpack (= 5.1.1)
      nio4r (~> 2.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.1.1)
      actionpack (= 5.1.1)
      actionview (= 5.1.1)
      activejob (= 5.1.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.1.1)
      actionview (= 5.1.1)
      activesupport (= 5.1.1)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.1.1)
      activesupport (= 5.1.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.1.1)
      activesupport (= 5.1.1)
      globalid (>= 0.3.6)
    activemodel (5.1.1)
      activesupport (= 5.1.1)
    activerecord (5.1.1)
      activemodel (= 5.1.1)
      activesupport (= 5.1.1)
      arel (~> 8.0)
    activesupport (5.1.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    addressable (2.5.1)
      public_suffix (~> 2.0, >= 2.0.2)
    arel (8.0.0)
    autoprefixer-rails (6.7.7.2)
      execjs
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    bindex (0.5.0)
    builder (3.2.3)
    byebug (9.0.6)
    capybara (2.13.0)
      addressable
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    childprocess (0.7.0)
      ffi (~> 1.0, >= 1.0.11)
    coderay (1.1.1)
    concurrent-ruby (1.0.5)
    config (1.4.0)
      activesupport (>= 3.0)
      deep_merge (~> 1.1.1)
    deep_merge (1.1.1)
    diff-lcs (1.3)
    dotenv (2.2.1)
    dotenv-rails (2.2.1)
      dotenv (= 2.2.1)
      railties (>= 3.2, < 5.2)
    erubi (1.6.0)
    erubis (2.7.0)
    execjs (2.7.0)
    faraday (0.12.1)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.18)
    globalid (0.4.0)
      activesupport (>= 4.2.0)
    hashie (3.5.5)
    httparty (0.14.0)
      multi_xml (>= 0.5.2)
    i18n (0.8.4)
    jbuilder (2.7.0)
      activesupport (>= 4.2.0)
      multi_json (>= 1.2)
    jquery-rails (4.3.1)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jwt (1.5.6)
    libv8 (3.16.14.19)
    listen (3.1.5)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
      ruby_dep (~> 1.2)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.6)
      mime-types (>= 1.16, < 4)
    material_design_lite-sass (1.3.0)
      autoprefixer-rails (~> 6.0)
      sass (~> 3.3)
    method_source (0.8.2)
    mime-types (3.1)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0521)
    mini_portile2 (2.2.0)
    minitest (5.10.2)
    multi_json (1.12.1)
    multi_xml (0.6.0)
    multipart-post (2.0.0)
    nio4r (2.1.0)
    nokogiri (1.8.0)
      mini_portile2 (~> 2.2.0)
    oauth2 (1.4.0)
      faraday (>= 0.8, < 0.13)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    omniauth (1.6.1)
      hashie (>= 3.4.6, < 3.6.0)
      rack (>= 1.6.2, < 3)
    omniauth-google-oauth2 (0.5.0)
      jwt (~> 1.5)
      multi_json (~> 1.3)
      omniauth (>= 1.1.1)
      omniauth-oauth2 (>= 1.3.1)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    pdf-core (0.7.0)
    pg (0.20.0)
    prawn (2.2.2)
      pdf-core (~> 0.7.0)
      ttfunk (~> 1.5)
    prawn-rails (1.0.0)
      prawn
      prawn-table
      rails (>= 3.1.0)
    prawn-table (0.2.2)
      prawn (>= 1.3.0, < 3.0.0)
    pry (0.10.4)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    pry-byebug (3.4.2)
      byebug (~> 9.0)
      pry (~> 0.10)
    pry-rails (0.3.6)
      pry (>= 0.10.4)
    public_suffix (2.0.5)
    rack (2.0.3)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.1.1)
      actioncable (= 5.1.1)
      actionmailer (= 5.1.1)
      actionpack (= 5.1.1)
      actionview (= 5.1.1)
      activejob (= 5.1.1)
      activemodel (= 5.1.1)
      activerecord (= 5.1.1)
      activesupport (= 5.1.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 5.1.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    railties (5.1.1)
      actionpack (= 5.1.1)
      activesupport (= 5.1.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.0.0)
    rb-fsevent (0.9.8)
    rb-inotify (0.9.8)
      ffi (>= 0.5.0)
    ref (2.0.0)
    rspec-core (3.6.0)
      rspec-support (~> 3.6.0)
    rspec-expectations (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-mocks (3.6.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.6.0)
    rspec-rails (3.6.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.6.0)
      rspec-expectations (~> 3.6.0)
      rspec-mocks (~> 3.6.0)
      rspec-support (~> 3.6.0)
    rspec-support (3.6.0)
    ruby_dep (1.5.0)
    rubyzip (1.2.1)
    sass (3.4.23)
    sass-rails (5.0.5)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    selenium-webdriver (3.4.1)
      childprocess (~> 0.5)
      rubyzip (~> 1.0)
    slop (3.6.0)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.1)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.0)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.3.13)
    therubyracer (0.12.3)
      libv8 (~> 3.16.14.15)
      ref
    thor (0.19.4)
    thread_safe (0.3.6)
    tilt (2.0.7)
    ttfunk (1.5.1)
    tzinfo (1.2.3)
      thread_safe (~> 0.1)
    uglifier (3.2.0)
      execjs (>= 0.3.0, < 3)
    web-console (3.5.1)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.2)
    xpath (2.1.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  better_errors
  byebug
  capybara (~> 2.13.0)
  config
  dotenv-rails
  httparty (= 0.14.0)
  jbuilder (~> 2.5)
  jquery-rails
  listen (>= 3.0.5, < 3.2)
  material_components_web-sass!
  material_design_lite-sass (= 1.3.0)
  omniauth-google-oauth2
  pg (= 0.20.0)
  prawn-rails
  pry-byebug
  pry-rails
  rails (~> 5.1.0)
  rspec-rails (~> 3.5)
  sass (= 3.4.23)
  sass-rails (= 5.0.5)
  selenium-webdriver
  spring
  spring-watcher-listen (~> 2.0.0)
  sqlite3
  therubyracer
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)

BUNDLED WITH
   1.14.6
```

**Comment by phillycheeze** [comment]
Also, my application.scss file:
```
/*
 * This is a manifest file that'll be compiled into application.css, which will include all the files
 * listed below.
 *
 * Any CSS and SCSS file within this directory, lib/assets/stylesheets, or any plugin's
 * vendor/assets/stylesheets directory can be referenced here using a relative path.
 *
 * You're free to add application-wide styles to this file and they'll appear at the bottom of the
 * compiled file so the styles you add here take precedence over styles defined in any other CSS/SCSS
 * files in this directory. Styles in this file should be added after the last require_* statement.
 * It is generally better to create a new file per style scope.
 *
 *= require_self
 *= require_tree .
 */
$color-primary: 0,173,211 !default;
$color-primary-dark: 22,60,74 !default;
$color-accent: 22,60,74 !default;

@import 'material';
@import 'material-components-web';
```

**Comment by rubysamurai** [comment]
In your `application.scss` file remove please that multiline top comment from `/*` to `*/` as it might cause problems with Sprockets and see if this helps.

**Comment by phillycheeze** [comment]
Still the same error unfortunately.

**Comment by rubysamurai** [comment]
I made a clean minimal Rails app

https://github.com/rubysamurai/mdcsasstest

Could you please pull it and see if it throws an error too? The app doesn't require any config.

**Comment by phillycheeze** [comment]
I tried your example app, and that compiles correctly! Let me look into why yours works and mine doesn't. I'll post an update after some research. Thanks!

**Comment by phillycheeze** [comment]
So the issue goes away if I remove the `material_design_lite-sass` gem in my Gemfile. There seems to be some conflict between these two gems. 

The weird thing is that even if I don't `@include 'material';` in my application.scss file, the error still happens. Just having the gem in the Gemfile (and subsequently required) is enough to cause the error. 

Does this happen to you as well? I need both gems as there are assets in both that I need.

**Comment by rubysamurai** [comment]
I've updated test rails app with latest `material_design_lite-sass` gem and so far can't reproduce the error. Trying some other assets related gems one by one and they don't trigger error too atm, but will keep testing.

**Comment by phillycheeze** [comment]
which order do you have the gems in the gemfile? I think I got the error when `material_design_lite-sass` was listed before `material_components_web-sass` in the Gemfile. 

Bundler.require() in config/application requires them in the order of the Gemfile I believe.

**Comment by phillycheeze** [comment]
I've given up on a solution for now. I am currently just including every component individually except the layout grid, since I don't need it for now.

**Comment by rubysamurai** [comment]
Unfortunately i tested both ways (mdc included first and mdl included first) 

Current [Gemfile](https://github.com/rubysamurai/mdcsasstest/blob/master/Gemfile) has `material_design_lite-sass` rquired before `material_components_web-sass`

Thank you a lot for patience and testing. I will keep trying to find a root of a problem, but so far it seems the best solution to include MDC in your project would be bypassing Rails assets pipeline via Webpacker. This also gives access to modular JavaScript inclusion of MDC.

**Comment by jankeesvw** [comment]
I am also experiencing this same problem. Right now i'm planning to use the compiled version of the css files, which is less than ideal.

**Comment by rubysamurai** [comment]
I still can't get a stable reproduction environment for the issue.

If you could provide a sample minimal app illustrating the error that would be a great help.

**Comment by jankeesvw** [comment]
I found a workaround, I noticed the problem only occurred in the test environment, I started digging and I found these lines in `sassc-rails`:

```ruby
initializer :setup_compression, group: :all do |app|
  if !Rails.env.development?
    app.config.assets.css_compressor = :sass unless app.config.assets.has_key?(:css_compressor)
  else
    # Use expanded output instead of the sass default of :nested unless specified
    app.config.sass.style ||= :expanded
  end
end
```
See: https://github.com/sass/sassc-rails/blob/63acddc25d527dedc0eda19afc84c56198c745ff/lib/sassc/rails/railtie.rb#L71:L76

Turns out `sassc-rails` does something different in the `!Rails.env.development?` environments. 

What I did to workaround this problem was to set a value in the css_compressor so it doest get overwritten, because it checks the `app.config.assets.has_key?(:css_compressor)` before overwriting it.

So by adding this to my `config/environments/test.rb` the problems went away:

```ruby
# Set a css_compressor so sassc-rails does not overwrite the compressor when running the tests
config.assets.css_compressor = nil
```

Hope this helps someone, I also created an issue here https://github.com/sass/sassc-rails/issues/93.

**Comment by mmics** [comment]
I had a very similar problem with my rails app and it turned out that there was an error in my css syntax in app/assets/stylesheets. I used scss-lint to find the issue. `scss-lint app/assets/stylesheets/ |grep "\[E\]"`
